{
	"version": 1587405184,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/game_backgroud-sheet0.png",
		"images/game_backgroud-sheet1.png",
		"images/game_backgroud-sheet2.png",
		"images/game_backgroud-sheet3.png",
		"images/game_backgroud-sheet4.png",
		"images/game_backgroud-sheet5.png",
		"images/game_backgroud-sheet6.png",
		"images/game_backgroud-sheet7.png",
		"images/game_backgroud-sheet8.png",
		"images/game_backgroud-sheet9.png",
		"images/img_-sheet0.png",
		"images/img_-sheet1.png",
		"images/img_-sheet2.png",
		"images/img_-sheet3.png",
		"images/img_-sheet4.png",
		"images/img_-sheet5.png",
		"images/uncle_-sheet0.png",
		"images/uncle_-sheet1.png",
		"images/arrow-sheet0.png",
		"images/board-sheet0.png",
		"images/button_ready-sheet0.png",
		"images/button_speed-sheet0.png",
		"images/light-sheet0.png",
		"images/light-sheet1.png",
		"images/signstart-sheet0.png",
		"images/sign_finish-sheet0.png",
		"images/vespa_character-sheet0.png",
		"images/vespa_character-sheet1.png",
		"images/vespa_character-sheet2.png",
		"images/vespa_character-sheet3.png",
		"images/vespa_character-sheet4.png",
		"images/vespa_character-sheet5.png",
		"images/vespa_character-sheet6.png",
		"images/vespa_character-sheet7.png",
		"images/vespa_character-sheet8.png",
		"images/vespa_character-sheet9.png",
		"images/vespa_character-sheet10.png",
		"images/vespa_character-sheet11.png",
		"images/vespa_character-sheet12.png",
		"images/vespa_character-sheet13.png",
		"images/vespa_character-sheet14.png",
		"images/vespa_character-sheet15.png",
		"images/vespa_characterwheel-sheet0.png",
		"images/vespa_characterwheel-sheet1.png",
		"images/vespa_characterwheel-sheet2.png",
		"images/vespa_characterwheel-sheet3.png",
		"images/vespa_characterwheel-sheet4.png",
		"images/vespa_characterwheel-sheet5.png",
		"images/buttonup-sheet0.png",
		"images/asset-sheet0.png",
		"images/asset2-sheet0.png",
		"images/asset2text-sheet0.png",
		"images/asset1balloon-sheet0.png",
		"images/asset3text-sheet0.png",
		"images/asset4text-sheet0.png",
		"images/whitefade-sheet0.png",
		"images/bg_-sheet0.png",
		"images/bg_-sheet1.png",
		"images/bg_-sheet2.png",
		"images/bg_-sheet3.png",
		"images/bg_-sheet4.png",
		"images/bg_-sheet5.png",
		"images/bg_-sheet6.png",
		"images/bg_-sheet7.png",
		"images/bg_-sheet8.png",
		"images/bg_-sheet9.png",
		"images/bg_-sheet10.png",
		"images/bg_-sheet11.png",
		"images/bg_-sheet12.png",
		"images/bg_-sheet13.png",
		"images/bg_-sheet14.png",
		"images/bg_-sheet15.png",
		"images/bg_-sheet16.png",
		"images/bg_-sheet17.png",
		"images/bg_-sheet18.png",
		"images/bg_-sheet19.png",
		"images/shadow-sheet0.png",
		"images/blackfade-sheet0.png",
		"images/skipclick-sheet0.png",
		"media/[bgm] race.ogg",
		"media/[bgm] tutorial.ogg",
		"media/[end_screen] detour_sting.ogg",
		"media/[ride] crash.ogg",
		"media/[ride] swish_lane.ogg",
		"media/[system] button_click.ogg",
		"media/[trafic_light] 3-2-1.ogg",
		"media/[trafic_light] start.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}